from decimal import Decimal

from api_runner import ApiRunner
from audit_models import VerificationResult
from evaluator import evaluate


def execute_ac003(base_url: str) -> dict:
    runner = ApiRunner(f"{base_url}/api/v1")

    # 1. Create a controlled test customer.
    customer_response = runner.post(
        "/customers",
        {
            "name": "Auditor Test Customer",
            "phone": "+256700000000",
            "email": "auditor@example.com",
            "address": "Auditor Test Address",
        },
    )

    if customer_response.status_code != 201:
        raise RuntimeError(
            f"Customer creation failed: "
            f"{customer_response.status_code} {customer_response.text}"
        )

    customer = customer_response.json()
    customer_id = customer["id"]

    # 2. Create an invoice using values controlled by the auditor.
    invoice_response = runner.post(
        "/invoices",
        {
            "customer_id": customer_id,
            "issue_date": "2026-09-17",
            "due_date": "2026-09-30",
            "items": [
                {
                    "description": "Auditor Item A",
                    "quantity": "2",
                    "unit_price": "100.00",
                },
                {
                    "description": "Auditor Item B",
                    "quantity": "1",
                    "unit_price": "50.00",
                },
            ],
            "notes": "Independent auditor runtime verification",
            "payment_terms": "Test only",
        },
    )

    if invoice_response.status_code != 201:
        raise RuntimeError(
            f"Invoice creation failed: "
            f"{invoice_response.status_code} {invoice_response.text}"
        )

    created_invoice = invoice_response.json()
    invoice_id = created_invoice["id"]

    # 3. Retrieve the created invoice from the running application.
    get_response = runner.get(f"/invoices/{invoice_id}")

    if get_response.status_code != 200:
        raise RuntimeError(
            f"Invoice retrieval failed: "
            f"{get_response.status_code} {get_response.text}"
        )

    observed = get_response.json()

    # 4. Independently calculate the expected values.
    quantity_a = Decimal("2")
    price_a = Decimal("100.00")

    quantity_b = Decimal("1")
    price_b = Decimal("50.00")

    line_total_a = quantity_a * price_a
    line_total_b = quantity_b * price_b

    subtotal = line_total_a + line_total_b
    tax = subtotal * Decimal("0.15")
    total = subtotal + tax

    expected = {
        "line_totals": [
            f"{line_total_a:.2f}",
            f"{line_total_b:.2f}",
        ],
        "subtotal": f"{subtotal:.2f}",
        "tax": f"{tax:.2f}",
        "total": f"{total:.2f}",
    }

    return {
        "invoice_id": invoice_id,
        "expected": expected,
        "observed": observed,
    }


def evaluate_ac003(execution: dict) -> list[VerificationResult]:
    expected = execution["expected"]
    observed = execution["observed"]

    observed_line_totals = [
        item["line_total"]
        for item in observed["items"]
    ]

    return [
        # VO-003-01 is a setup action generated by the planner,
        # not an independently evaluated assertion.
        VerificationResult(
            obligation_id="VO-003-01",
            status="UNVERIFIED",
            evidence=None,
            reason=(
                "The planner produced this as a setup action rather than "
                "an independently evaluated assertion."
            ),
        ),

        # Verify line totals.
        evaluate(
            "VO-003-02",
            expected["line_totals"],
            observed_line_totals,
            "runtime-api",
        ),

        # Verify subtotal.
        evaluate(
            "VO-003-03",
            expected["subtotal"],
            observed["subtotal"],
            "runtime-api",
        ),

        # Verify 15% tax.
        evaluate(
            "VO-003-04",
            expected["tax"],
            observed["tax"],
            "runtime-api",
        ),

        # Verify final invoice total.
        evaluate(
            "VO-003-05",
            expected["total"],
            observed["total"],
            "runtime-api",
        ),
    ]